- name: install basic packages
  yum:
    name:
      - unzip
      - centos-release-ansible-27.noarch
    state: latest

- name: install ansible
  yum:
    name:
      - ansible
    state: present
    
- name: remove packer binary from crackerlibs
  file:
    path: /usr/sbin/packer
    state: absent

- name: download packer
  get_url:
    url: https://releases.hashicorp.com/packer/1.5.1/packer_1.5.1_linux_amd64.zip
    dest: /tmp/packer_1.5.1_linux_amd64.zip

- name: extract packer
  unarchive:
    src: /tmp/packer_1.5.1_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes

- name: add packer user to docker group 
  user:
    name: packer
    group: docker
    state: present
