- name: provision python
  hosts: all
  gather_facts: no
  tasks:
    - name: Boostrap python
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)

- name: run custom config on the docker image
  hosts: all
  tasks:
    - name: create workdir
      file:
        path: /data
        state: directory
        owner: root
        group: root
        mode: 0755

- name: container cleanup
  hosts: all
  gather_facts: no
  tasks:
    - name: Remove python
      raw: apt-get purge -y python-minimal && apt-get autoremove -y
    - name: Remove apt lists
      raw: rm -rf /var/lib/apt/lists/*
