- name: run custom config on the docker image
  hosts: all

  tasks:

    - name: create workdir
      file:
        path: /data
        state: directory
        owner: root
        group: root
        mode: 0755
